### ISSUE TITLE
`NullPointerException` when `SubscriptionRepository` receives an update for a topic deleted from the local health log

### ISSUE THREAD

**Issue by dmitrykuzmin** [SpineEventEngine/web#202]
We currently have a multi-instance setup where, as expected, all instances share the same set of subscriptions for model changes. 

When one of the instances handles a subscription cancel request and deletes the subscription node from Firebase, all others react to the `onChildRemoved` Firebase event and remove the subscription topic from their local health log. However, on these machines, the local `SubscriptionService` was never asked to cancel the subscription for the topic, and the update observer continues to receive the subscription updates. 

All updates received this way produce the `NullPointerException` in the `HealthLog.isStale(Topic)` call, as the health log expects the topic to be known, while in reality, it was removed from the said health log after the subscription has been canceled or was found to be stale on another machine.

The exception stack trace:
```
io.spine.server.stand.EntityChangeHandler - java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:994) ~[server-frontend.jar:1.0.0]
	at io.spine.web.firebase.subscription.HealthLog.isStale(HealthLog.java:116) ~[server-frontend.jar:1.0.0]
	at io.spine.web.firebase.subscription.UpdateObserver.onNext(UpdateObserver.java:62) ~[server-frontend.jar:1.0.0]
	at io.spine.web.firebase.subscription.UpdateObserver.onNext(UpdateObserver.java:44) ~[server-frontend.jar:1.0.0]
	at io.spine.server.stand.SubscriptionCallback.lambda$forwardingTo$0(SubscriptionCallback.java:52) ~[server-frontend.jar:1.0.0]
	at io.spine.server.stand.UpdateHandler.deliverUpdate(UpdateHandler.java:105) ~[server-frontend.jar:1.0.0]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at io.spine.server.stand.UpdateHandler.handle(UpdateHandler.java:85) ~[server-frontend.jar:1.0.0]
	at io.spine.server.stand.SubscriptionRecord.update(SubscriptionRecord.java:130) ~[server-frontend.jar:1.0.0]
	at io.spine.server.stand.EventTap.lambda$accept$0(EventTap.java:57) ~[server-frontend.jar:1.0.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at io.spine.server.stand.EventTap.accept(EventTap.java:57) ~[server-frontend.jar:1.0.0]
	at io.spine.server.stand.EventTap.accept(EventTap.java:39) ~[server-frontend.jar:1.0.0]
	at io.spine.server.bus.Listeners.lambda$accept$0(Listeners.java:55) ~[server-frontend.jar:1.0.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.spine.server.bus.Listeners.accept(Listeners.java:53) ~[server-frontend.jar:1.0.0]
	at io.spine.server.bus.Bus.lambda$post$1(Bus.java:150) ~[server-frontend.jar:1.0.0]
	at java.util.Col… [message truncated due to size]
```

**Comment by armiol** [comment]
@dmitrykuzmin @YegorUdovchenko please confirm this is now addressed.

**Comment by dmitrykuzmin** [comment]
@armiol The bug hasn't surfaced since we updated to the latest version, so probably resolved.

**Comment by YegorUdovchenko** [comment]
> @dmitrykuzmin @YegorUdovchenko please confirm this is now addressed.
Pure Photos has used the updated version for two days in production and didn't get such exceptions.
